config/routes.rb
Rails.application.routes.draw do
  get 'statics/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'statics/ajax_update', to: 'statics#ajax_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def top
    @id = 1
    @body = Content.find(@id).body
  end
  def ajax_update
    # topページにある「data(入力フォーム)」のパラメーターを@textに代入
    @text = params[:data]
    @kousin = "(データが更新されました!)"
    num = params[:num]
    content = Content.find(num)
    content.body = @text
    content.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statics/ajax_update.js.erb
var content = '<%= "#{ @text }" %>'
var kousin = '<%= "#{ @kousin }" %>'
$('#ajax-test').text(content);
$('#ajax-test2').text(kousin);

app/views/statics/top.html.erb
 <!-- 見出し -->
<h1>Statics#top</h1>

<!--  タグでファイル名を表示  -->
<p>Find me in app/views/statics/top.html.erb</p>

<!--  デフォルトで表示されている内容  -->
ajaxtest:<div id="ajax-test" class="tmp2nd">
   <%=@body %>
</div>
 <div id="ajax-test2" class="tmp2nd">
</div>
<!--  入力フォームをform_withで作成  -->
<div id="ajax-request">
  <!-- form_withのパスを「ajax_updateアクション」に紐付ける -->
  <%= form_with url: statics_ajax_update_path do |f| %>
    <!--  入力フォーム  -->
    <%= f.text_field :data,id:"content", required: true %>
    <%= hidden_field_tag :num, @id  %>
    <!--  送信ボタン  -->
    <%= f.submit 'Post Ajax' %>
    <button type="button" id="inputClearBtn">入力をクリアする</button>
    
  <% end %>
</div>

<style>
    div.tmp2nd {display: inline-block; _display: inline;}
</style>

<script>
$(function() {
    $("#inputClearBtn").click(function() {
        $("#content").val("");
    });
});
</script>